### ISSUE TITLE
Extension to work outside of RStudio

### ISSUE THREAD

**Issue by cimentadaj** [MilesMcBain/breakerofchains#1]
Great job @MilesMcBain! This would fit super nicely within Emacs/Spacemacs, binding `break_chain` to a key binding. However, the current implementation only works with RStudio. Any interest in making it work outside of RStudio. I guess eveything should work out of the box except for the `rstudioapi` calls from here:

https://github.com/MilesMcBain/breakerofchains/blob/cab667ad1fd46fee1a4113e0c6d05a6be3f02c82/R/chain_break.R#L8-L25

I'm not entirely sure how it could be done but getting `doc_lines` should be straight forward, just a `readLines` of the file. The problem I see is figuring out where is the cursor at the time of execution. Do you have any ideas how to get the cursor from outside RStudio?

**Comment by MilesMcBain** [comment]
It's actually easier in just about every other editor than RStudio to do stuff with cursor position. There's lots of helpful functions in Emacs for it. I made an Elisp interface for another addin (`{fnmate}`) that made similar RStudio API calls.

Check out the Elisp here for some ideas:

https://github.com/MilesMcBain/fnmate/blob/master/vignettes/ess_bindings.Rmd

**Comment by cimentadaj** [comment]
Thanks! Yeah, I was thinking of doing it in raw elisp but wondering whether it was possible to get that from R itself such that it can work in other editors such as VSCode. But anyways, after thinking about it, doesn't really make sense for R to know that since it is agnostic with respect to the editor (so there shouldn't have any support for that). Thanks!

**Comment by MilesMcBain** [comment]
In case you didn't know RStudio addins are supported in VSCode and this will work when this PR gets merged: https://github.com/Ikuyadeu/vscode-R/pull/535

**Comment by atanasj** [comment]
@cimentadaj, I know this issue is closed, but wondering if you wrote some code to get this working... I'm looking to poach!

**Comment by cimentadaj** [comment]
@atanasj this is what I implemented and it seems to work

```

    (defun highlight-piped-region ()
      (let ((end (point))
            (beg (pos-paragraph)))
          (set-mark beg)
          (goto-char end)
          (end-of-line)
          (deactivate-mark)
          (setq last-point (point))
          (goto-char end)
          (buffer-substring-no-properties beg last-point)))

    (defun run-partial-pipe ()
      (interactive)
      (let ((string-to-execute (highlight-piped-region)))
        ;; https://stackoverflow.com/questions/65882345/replace-last-occurence-of-regexp-in-a-string-which-has-new-lines-replace-regexp/65882683#65882683
        (ess-eval-linewise
         (replace-regexp-in-string
          ".+<-" "" (replace-regexp-in-string
                     "\\(\\(.\\|\n\\)*\\)\\(%>%\\|\+\\) *\\'" "\\1" string-to-execute)))))

    (define-key ess-mode-map (kbd "<C-S-return>") 'run-partial-pipe)

```

**Comment by atanasj** [comment]
@cimentadaj, thanks for that. But I'm getting an error: 

```lisp
Symbol's function definition is void: pos-paragraph
```

Any idea why this may be? I'm using `doom` emacs btw, so not sure if it is some difference between Spacemacs (if that's what you're using).

**Comment by cimentadaj** [comment]
Sorry, I forgot to add that function as well:

```

    (defun pos-paragraph ()
      (backward-paragraph)
      (next-line 1)
      (beginning-of-line)
      (point))
```

I think that should work @atanasj
