### ISSUE TITLE
object 'breakerofchains_store_result' not found

### ISSUE THREAD

**Issue by yjunechoe** [MilesMcBain/breakerofchains#11]
I get the following error when running the add-in command:

**Error in getOption(breakerofchains_store_result, TRUE) :    object 'breakerofchains_store_result' not found**

Not sure if it's something about my setup, but maybe `breakerofchains_store_result` in this line should be a character not a variable -`"breakerofchains_store_result"`?

https://github.com/MilesMcBain/breakerofchains/blob/3d3a4558707b6e0d81ff3ecefcd8d768a082ed2e/R/chain_break.R#L26

Edit: oops just seeing a PR addressing this same thing. I think that'll fix the issue if it gets merged

**Comment by MilesMcBain** [comment]
It should and I think I fixed this but didn't push! Thanks.

**Comment by MilesMcBain** [comment]
Actually I forgot to commit, classic. All fixed now.
