### ISSUE TITLE
Shorten package name

### ISSUE THREAD

**Issue by krlmlr** [MilesMcBain/breakerofchains#12]
How about {houdini}?

**Comment by krlmlr** [comment]
I wasn't aware of the UrbanDictionary "definition"...

**Comment by MilesMcBain** [comment]
🤣 

When I was a kid that word did have a UrbanDictionary meaning but it was more toilet humour than sexual.

There are some not entirely unappealing shorter names based on `unchained` or `unshackled` or something. But to me it's a kind of ridiculous package that deserves a ridiculous name. 

What motivated the issue?

**Comment by krlmlr** [comment]
I remembered the famous breaker of chains and didn't run `available::available()` before posting. The name is fine as is.
