### ISSUE TITLE
Suggestion: show error in console, not GUI

### ISSUE THREAD

**Issue by jzadra** [MilesMcBain/breakerofchains#17]
Currently if I use my keyboard shortcut to activate the addin and it fails for any reason, I get a GUI dialog box I have to interact with. It would be preferable to just show an error in the console rather than stealing the focus.

![image](https://user-images.githubusercontent.com/25590353/152240356-ce0c0bcf-7100-41fe-8ab5-a3063df105e8.png)

**Comment by MilesMcBain** [comment]
Thanks! I didn't realise this was happening because I've never seen it in VSCode.

**Comment by jzadra** [comment]
Sure! Not sure what you mean about VSCode though, this is in R/Rstudio

**Comment by MilesMcBain** [comment]
I only mean I use the addin in VSCode, which supports R and RStudio add-ins. But in VSCode add-in errors don't throw modal dialogues.

**Comment by jzadra** [comment]
Gotcha.  Well I love this addin, happy to help test.  I am working on some useful things to do wtih the .chain object afterwards too that i'll share if they turn out ok (data summary type things; glimpse(), visdat, etc)
