### ISSUE TITLE
Error in "Break Chain and run to cursor" (with dplyr 1.1.0)

### ISSUE THREAD

**Issue by AlvaroMCMC** [MilesMcBain/breakerofchains#22]
I've just updated to `dplyr` 1.1.0 and when I try to run `Break Chain and run to cursor` this error shows up:

```
Error in `dplyr::lead()`:
! Can't convert from `default` <double> to `x` <integer> due to loss of precision.
• Locations: 1
Run `rlang::last_error()` to see where the error occurred.
---
Backtrace:
 1. breakerofchains:::break_chain()
 5. breakerofchains:::polyfill_base_pipe(.)
 6. dplyr::lead(source_tokens$row, default = Inf)
````

**Comment by MilesMcBain** [comment]
Thanks for taking the time to raise an issue. This has been fixed for a while, so please update your package version.

Also, in the future, you can reduce the burden on open source software maintainers by doing any or all of:

1. Checking the NEWS file
2. Trying the latest version
3. Searching for similar closed issues on the Github repository.
