### ISSUE TITLE
Division operator being substituted 

### ISSUE THREAD

**Issue by wheelern** [MilesMcBain/breakerofchains#6]
I love everything about this; thanks for the idea and implementation. 

It looks to me like the division operator is being substituted (maybe a bug in the regex looking for pipes?).

    starwars %>%
      group_by(species, sex) %>%
      select(height, mass) %>%
      mutate(BMI = mass / ((height / 100) ^ 2)) %>% 
      summarise(
        height = mean(height, na.rm = TRUE),
        mass = mean(mass, na.rm = TRUE)
      ) %>%
      ggplot(aes(x = height, y = mass)) +
      geom_point()

Running anything after the mutate results in:

    Error: unexpected numeric constant in:
    "  select(height, mass) %>%
    mutate(BMI = mass  ((height  100"

**Comment by MilesMcBain** [comment]
Oh good catch thanks!
