### ISSUE TITLE
Option to skip assignment when breaking chain

### ISSUE THREAD

**Issue by nwbort** [MilesMcBain/breakerofchains#7]
It would be great to have an option to skip assignment and just print the results when breaking chains.

For example, breaking the code below on the `select` line currently saves the output of the shortened chain to the `species_scatter` variable, but it would be great to instead skip the assignment (ie, make it equivalent to the same code without `species_scatter <- `)

```
species_scatter <- starwars %>%
    group_by(species, sex) %>%
    select(height, mass) %>%
    summarise(
        height = mean(height, na.rm = TRUE),
        mass = mean(mass, na.rm = TRUE)
    ) %>%
    ggplot(aes(x = height, y = mass)) +
    geom_point()
```

I find that I'm often running code chunks like this when reviewing my own or other's code.

**Comment by MilesMcBain** [comment]
I think this is most useful, yes!

So as things are currently this won't run the assignment: 

```
species_scatter <- 
    starwars %>%
    group_by(species, sex) %>%
    select(height, mass) %>%
    summarise(
        height = mean(height, na.rm = TRUE),
        mass = mean(mass, na.rm = TRUE)
    ) %>%
    ggplot(aes(x = height, y = mass)) +
    geom_point()
```
But because it works by lines, and not by expression (a bit easier), the first line is run in your example.

**Comment by MilesMcBain** [comment]
I'll try and introduce some special handling for line 1, since I think the style you have there is not uncommon.

**Comment by nwbort** [comment]
Ah, good to know that keeping assignment on the previous line will work as-is - but yes, that's the style I'm most familiar with (and eg is one of the 'acceptable' forms of assignment from the tidyverse style guide).

The add-in is great though - thanks

**Comment by MilesMcBain** [comment]
All done thanks!

**Comment by nwbort** [comment]
Works well thanks with one new bug/unexpected behaviour in an awkward edge case.

If the previous line of code is a comment ending with `-` the special case doesn't work.

MWE:

```
# This works
species_scatter <- starwars %>%
    group_by(species, sex) %>%
    select(height, mass)

# But this doesn't -
species_scatter <- starwars %>%
    group_by(species, sex) %>%
    select(height, mass)
```

(the context is that I use `-` to end section headings)

**Comment by MilesMcBain** [comment]
Ooof that's odd. I assumed comments would be ignored by the parser but I didn't look. Thanks!

**Comment by MilesMcBain** [comment]
Okay this is a bit of a can of worms. I think comments are handled somewhat predictably now.

* Comments up in the midst of the chain do not affect anything
* Comments above the chain do not affect anything
* Comment lines on or above the break line are removed (upward) until a code line is hit.
* Comments at the end of a break line that contains code are removed with the chaining op.
